API_ID: 2497276
API_HASH: 78122b16901bda6c500eebe931b31d42
BOT_TOKEN: 5621108899:AAF92StgpVU6FD88bPChbqZeWTDGomYsZcc


MONGO_URL: mongodb+srv://cccheck:checkerpy@cluster0.kar4eo2.mongodb.net/?retryWrites=true&w=majority
REDIS_URI: redis-16550.c53.west-us.azure.cloud.redislabs.com
REDIS_PORT: 16550
REDIS_PASS: rL1culHTprVJH91J55OQxapHH6qYPYrv

SESSION_API_ID: 2497276
SESSION_API_HASH: 78122b16901bda6c500eebe931b31d42
SESSION_STRING: 1BVtsOKQBuyxa9YEYQpCi3PrciF50dd5BZ_sj8sOrIkVBtf8c5R__kyXpEqJBH4TOT3p7KyPX51Kb9GRXt5iMJA_b0EsuXDRY589EYmsodO-yYY4FWrNboxIoePHTi1BMlYRKe4nq1gL94084aDqQaSdKzTAVLK7xZTVWih9n7ZMeNAuOlD7vwvBLun6NEAo38SckXX1RTSzLu1m8oyaOoT0e36fHFqnD1-3y_JIhh3aTMVvslWCTGiwSfTEmOIkg1JQZMdyVKQR-UirYWcgxHApjjJ_tcArDDiazL7eLeOod1F0qLT4V45vJcniNVwcrnQU_YlFy_0fps1ZYXia5gQZ2u8sneRM=

ADMINS: 
  - 1789859817

OWNER: 1789859817

BOT_PIC: https://te.legra.ph/file/280c6f1a2fbf10caf0822.jpg
OWNER_PIC: https://telegra.ph/file/21d1cdfd3714aff7124c6.jpg


SUPPORT_CHAT: Suzune_Support
# LOG_CHAT: 
LOG_CHAT: -1001665081502



HANDLERS: 
  - "."
  - "!"
  - "/"
  - "?"
  - "~"

